modern-agile-team/6term-main-back

- src/auth/controllers/auth.controller.ts
- src/auth/entities/token.entity.ts
- src/auth/services/auth.service.ts
- src/config/typeorm.config.ts
- src/users/repositories/user.repository.ts
사용자가 DB에 있는지 체크하고 이름과 이미지를 수정하는 로직에서 제대로 유저를 찾지 못하는 오류를 수정하였습니다.
> Fix(NicoDora/auth): 사용자 체크 오류 수정

- src/auth/controllers/auth.controller.ts
- src/auth/services/token.service.ts
- src/main.ts
**axios를 통해 소셜 로그인의 로그아웃, 회원탈퇴를 구현하였습니다.**
소셜 토큰 유효성 검사, 소셜 토큰 재발급 로직이 포함되어 있습니다.
> Add(NicoDora/auth) : axios를 통한 로그아웃, 회원탈퇴 구현

- src/auth/controllers/auth.controller.ts
> Tset(NicoDora/auth) : 카카오 로그인 테스트

- src/chat/controllers/chat.controller.ts
- src/chat/dto/post-chat.dto.ts
- src/chat/dto/received-user.dto.ts
- src/chat/parse-object-id.pipe.ts
- src/chat/repositories/chat.repository.ts
- src/chat/schemas/chat-image.schemas.ts
- src/chat/schemas/chat-notifiation.schemas.ts
- src/chat/schemas/chat.schemas.ts
- src/chat/services/chat.service.ts
- src/http-Exception.filter.ts
- src/main.ts
전체적으로 try/catch 불필요한거 삭제했고 return await은 에러 핸들링이 필요한 한군데 제외하고 전부 삭제했습니다. HttpExceptionFilter 적용 했습니다.
> Refactor(hobiJeong/socket): 코드 리팩터링

- src/chat/controllers/chat.controller.ts
- src/events/events.gateway.ts
> Refactor(hobiJeong/socket) SubcscribeMessage login 추가(socket.join)

- src/app.module.ts
- src/config/swagger.ts
- src/config/typeorm.config.ts
- src/friend/friend.module.ts
- src/friends/controllers/friends.controller.ts
- src/friends/entities/friends.entity.ts
- src/friends/friends.module.ts
- src/friends/repositories/friends.repository.ts
- src/friends/services/friends.service.ts
- src/main.ts
친구 요청 기능을 추가하였습니다.
friend 엔티티가 수정되어서 pr 올립니다.
> Add(NicoDora/friend) : 친구 요청 기능 추가

- src/auth/services/auth.service.ts
- src/chat/schemas/chat-notifiation.schemas.ts
- src/friends/controllers/friends.controller.ts
- src/friends/repositories/friends.repository.ts
- src/friends/services/friends.service.ts
- src/friends/swagger-decorators/friend-request.docorator.ts
- src/friends/swagger-decorators/get-friends-req-pending.decorator.ts
- src/friends/swagger-decorators/get-friends.docorator.ts
- src/notice/entities/board-notice.entity.ts
- src/notice/entities/comment-notice.entity.ts
1. API 명세서를 작성했습니다.
2. 각 API들의 엔드포인트를 수정했습니다.
3. 알람관련 엔티티를 수정했습니다.
> Add(NicoDora/friends) : API 명세서 작성 및 엔드포인트 수정

- src/friends/controllers/friends.controller.ts
- src/friends/repositories/friends.repository.ts
- src/friends/services/friends.service.ts
- src/friends/swagger-decorators/get-friends-res-pending.decorator.ts
- src/friends/swagger-decorators/get-friends.docorator.ts
- src/users/controllers/user-image.controller.ts
1. 내가 받은 친구 요청 조회 API를 추가했습니다.
2. API 명세서도 추가했습니다.
> Add(NicoDora/friend) : 내가 받은 친구 요청 조회 API 추가

- src/auth/controllers/auth.controller.ts
- src/auth/services/token.service.ts
> Fix(NicoDora/auth) : 카카오 로그아웃 에러 수정

- src/friends/controllers/friends.controller.ts
- src/friends/repositories/friends.repository.ts
- src/friends/services/friends.service.ts
- src/friends/swagger-decorators/friend-response-reject.decorator.ts
> Add(NicoDora/friends) : 친구 요청 거절하기 API 추가

- src/boards/controllers/boards-like.controller.ts
- src/boards/entities/board-like.entity.ts
- src/boards/repository/boards-like.repository.ts
- src/boards/services/boards-like.service.ts
- src/friends/controllers/friends.controller.ts
- src/friends/repositories/friends.repository.ts
- src/friends/services/friends.service.ts
- src/friends/swagger-decorators/delete-friend.decorator.ts
- src/friends/swagger-decorators/friend-request.decorator.ts
- src/friends/swagger-decorators/friend-response-reject-permanent.decorator.ts
친구 삭제 API를 추가했습니다.
친구 요청 영구 거절 기능을 추가했습니다.
> Add(NicoDora/friends) : 친구 삭제 API 추가

- src/friends/controllers/friends.controller.ts
- src/friends/repositories/friends.repository.ts
- src/friends/services/friends.service.ts
- src/friends/swagger-decorators/delete-reject-permanent-cancel.decorator.ts
- src/friends/swagger-decorators/get-reject-permanent.decorator.ts
영구거절한 친구 요청 불러오기 및 영구거절 취소 API를 추가했습니다.
> Add(NicoDora/friends) : 영구거절한 친구 요청 불러오기 및 영구거절 취소 API 추가.

- src/users/controllers/user.controller.ts
- src/users/repositories/user.repository.ts
- src/users/services/user.service.ts
- src/users/swagger-decorators/get-user-info.decorator.ts
- src/users/user.module.ts
유저 id로 유저 정보(name, Image) 얻기 API 추가했습니다.
> Add(NicoDora/user) : user 정보 얻기 API 추가.

- src/friends/entities/friends.entity.ts
- src/friends/repositories/friends.repository.ts
친구 요청 후 쿨타임을 넣기 위해 엔티티를 수정했습니다.
> Fix(NicoDora/friend) : 친구 엔티티 수정

- package-lock.json
- package.json
- src/app.module.ts
- src/friends/controllers/friends.controller.ts
- src/friends/repositories/friends.repository.ts
- src/friends/services/friends.service.ts
친구요청을 거절당하면 다시 친구요청을 보낼때 쿨타임(24시간)을 추가했습니다.
그리고 UTC기준 00시(KST 오전 9시)에 친구 요청이 거절당하고 24시간이 지난 로우들은 삭제하는 로직을 @nestjs/schedule을 이용하여 구현했습니다.
> Add(NicoDora/friend) : 친구요청 거절당했으면 쿨타임 추가

- src/boards/controllers/boards-like.controller.ts
- src/boards/repository/boards-like.repository.ts
- src/boards/services/boards-like.service.ts
- src/boards/swagger-decorators/get-board-like-count.decorator.ts
비로그인으로 토큰값이 없을 경우에도 좋아요 개수를 가져오는 로직을 실행하도록 catch로 핸들링
> Refactor(hobiJeong/board-like) : 좋아요 조회 시, 해당 유저가 좋아요를 눌렀는지 판별하는 코드 추가

- src/common/notice/repositories/notice.repository.ts
hard-delete는 하지 않는 방향으로 추진하고 가장 최근의 알람 10개만 받아오도록 수정 했습니다.
> Refactor(hobiJeong/notice) 알람 받아올 시 가장 최근 알람의 10개만 받아오도록 수정.

- src/auth/controllers/auth.controller.ts
프론트에서 토큰 만료 여부를 판단하기 위한 API가 하나 필요하다고 해서 추가했습니다.
> Add(NicoDora/auth) : 프론트에서 토큰 만료 여부 판단 API 추가

- src/friends/controllers/friends.controller.ts
friend API쪽에 토큰 가드와 GetUserId 데코레이터를 적용했습니다.
> Refactor(NicoDora/friend) : 토큰가드와 GetUserId 데코레이터 적용

- src/auth/controllers/auth.controller.ts
- src/comments/entities/comment.entity.ts
- src/users/services/user.service.ts
> Modify(NicoDora/auth): 내정보 가져오기 API 반환값에 id 추가

- src/comments/entities/recomment.entity.ts
- src/friends/controllers/friends.controller.ts
- src/friends/entities/friends.entity.ts
- src/friends/repositories/friends.repository.ts
- src/friends/services/friends.service.ts
- src/friends/swagger-decorators/delete-friend.decorator.ts
- src/friends/swagger-decorators/delete-reject-permanent-cancel.decorator.ts
- src/friends/swagger-decorators/friend-response-accept.decorator.ts
- src/friends/swagger-decorators/friend-response-reject-permanent.decorator.ts
- src/friends/swagger-decorators/friend-response-reject.decorator.ts
- src/friends/swagger-decorators/get-friends-req-pending.decorator.ts
- src/friends/swagger-decorators/get-friends-res-pending.decorator.ts
- src/friends/swagger-decorators/get-friends.decorator.ts
- src/friends/swagger-decorators/get-reject-permanent.decorator.ts
GET API에서 상대방 이름과 이미지 가져오는 기능을 추가했습니다.
> Modify(NicoDora/friend) : GET API에서 상대방 이름과 이미지 가져오는 기능 추가

- src/auth/services/token.service.ts
- src/users/services/user.service.ts
- src/users/swagger-decorators/get-my-info-decorator.ts
내정보GET API에 내 아이디를 id -> userId로 수정했습니다.
> Modify(NicoDora/user): 내정보GET API에 내 아이디를 userId로 명시

- src/auth/controllers/auth.controller.ts
- src/config/guards/jwt-access-token.guard.ts
배포 후에 프론트에서 리프레시 토큰이 담긴 쿠키가 오지 않는 문제를 해결했습니다.
> Fix(NicoDora) : 배포후 쿠키에 토큰이 담기지 않는 문제 해결

- src/auth/controllers/auth.controller.ts
> Test(NicoDora/auth): httponly 설정 삭제

- src/main.ts
> Test(NicoDora/auth) : 쿠키cors설정

- src/auth/controllers/auth.controller.ts
> Test(NicoDora/auth) : sameSite 설정 추가

- src/friends/repositories/friends.repository.ts
> Fix(NicoDora) : 친구요청 영구거절 상태 수정

- src/comments/controllers/comments.controller.ts
보드와 댓글 컨트롤딴에 데코레이터 수정 완료했습니다
- 보드는 비호형 pr에 같이 딸려갔어용-
> Refactor(2swo/Comment) Comment controller 커스텀데코레이터 적용

- src/chat/controllers/chat.controller.ts
- src/chat/events/events.gateway.ts
- src/chat/services/chat.service.ts
- src/common/interceptors/success-response.interceptor.ts
- src/common/s3/s3.service.ts
- src/config/guards/web-socket-jwt-access-token.guard.ts
WebSocketGateway쪽 에서의 경우 아직 구현하지 못했습니다.
> Modify(hobiJeong/socket): Response의 형식을 통일시키기 위해서 interceptor를 추가 했습니다.
